In [96]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [97]:
df = pd.read_csv("Wine.csv")

In [98]:
Y =df["Customer_Segment"]
X=df[df[df.columns]!="Customer_Segment"]

In [99]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=0,test_size=0.33)

In [100]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# LCA- Bu kolonlar daha az sayıya indirilebilir mi? Gözetimli olarak

In [101]:
lda = LDA(n_components=1)
X_train_lda = lda.fit_transform(X_train,Y_train)
X_test_lda = lda.transform(X_test)

In [102]:
from sklearn.linear_model import LogisticRegression

# Düzenlenmiş Linear Model

In [103]:
logreg = LogisticRegression(random_state=0)
logreg.fit(X_train_lda,Y_train)

c:\Users\Özdemir\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [104]:
y_pred_lda = logreg.predict(X_test_lda)

In [105]:
from sklearn.metrics import confusion_matrix

In [106]:
cm = confusion_matrix(y_pred=y_pred_lda,y_true=Y_test)
cm

array([[20,  0,  0],
       [24,  0,  0],
       [15,  0,  0]], dtype=int64)

In [107]:
logreg2 = LogisticRegression(random_state=0)
logreg2.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [108]:
y_pred = logreg2.predict(X_test)

In [109]:
cm = confusion_matrix(y_pred=y_pred,y_true=Y_test)
cm

array([[20,  0,  0],
       [ 0, 24,  0],
       [ 0,  0, 15]], dtype=int64)

In [110]:
cm2 = confusion_matrix(y_pred,y_pred_lda)
cm2

array([[20,  0,  0],
       [24,  0,  0],
       [15,  0,  0]], dtype=int64)