In [272]:
import pandas as pd
import numpy as np
import seaborn as sns
import re
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [273]:
df = pd.read_csv("Restaurant_Reviews.csv",error_bad_lines=False,sep=",")
df.dropna(axis=0,inplace=True)

C:\Users\Özdemir\AppData\Local\Temp\ipykernel_18064\430955801.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv("Restaurant_Reviews.csv",error_bad_lines=False,sep=",")
Skipping line 15: expected 2 fields, saw 4
Skipping line 20: expected 2 fields, saw 3
Skipping line 23: expected 2 fields, saw 3
Skipping line 29: expected 2 fields, saw 3
Skipping line 30: expected 2 fields, saw 3
Skipping line 32: expected 2 fields, saw 4
Skipping line 35: expected 2 fields, saw 3
Skipping line 36: expected 2 fields, saw 3
Skipping line 39: expected 2 fields, saw 3
Skipping line 45: expected 2 fields, saw 3
Skipping line 46: expected 2 fields, saw 3
Skipping line 49: expected 2 fields, saw 3
Skipping line 51: expected 2 fields, saw 3
Skipping line 55: expected 2 fields, saw 3
Skipping line 57: expected 2 fields, saw 4
Skipping line 60: expected 2 fields, saw 3
Skipping line 61: expected 2 f

In [274]:
yorum = [re.sub('[^a-zA-Z]',' ',i) for i in df["Review"]]

In [275]:
df["Review"] = yorum

In [276]:
df["Review"]

0                               Wow    Loved this place 
1                                     Crust is not good 
2              Not tasty and the texture was just nasty 
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
711              the presentation of the food was awful 
712             I can t tell you how disappointed I was 
713    I think food should have flavor and texture an...
714                             Appetite instantly gone 
715    Overall I was not impressed and would not go b...
Name: Review, Length: 704, dtype: object

In [277]:
buyuk_kucuk = df["Review"].str.lower()


In [278]:
buyuk_kucuk = buyuk_kucuk.str.split()
df["Review"] = buyuk_kucuk

In [279]:
df["Review"]

0                              [wow, loved, this, place]
1                                 [crust, is, not, good]
2      [not, tasty, and, the, texture, was, just, nasty]
3      [stopped, by, during, the, late, may, bank, ho...
4      [the, selection, on, the, menu, was, great, an...
                             ...                        
711       [the, presentation, of, the, food, was, awful]
712    [i, can, t, tell, you, how, disappointed, i, was]
713    [i, think, food, should, have, flavor, and, te...
714                          [appetite, instantly, gone]
715    [overall, i, was, not, impressed, and, would, ...
Name: Review, Length: 704, dtype: object

In [280]:
ps = PorterStemmer()

In [281]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Özdemir\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [282]:
from nltk.corpus import stopwords

In [283]:
yorum = list()
derlem = list()
for satır in df["Review"]:
    yorum = [ ps.stem(kelime)for kelime in satır if not kelime in set(stopwords.words("english"))]         
    
    yorum = " ".join(yorum)
    derlem.append(yorum)


In [284]:
from sklearn.feature_extraction.text import CountVectorizer

In [285]:
cv = CountVectorizer(max_features=2000)


In [286]:
X =cv.fit_transform(derlem).toarray()


In [287]:
y = df["Liked"].values

In [288]:
X_train,X_test,Y_train,Y_test = train_test_split(X,
y,
random_state=0,
test_size=0.20)

In [289]:
from sklearn.naive_bayes import GaussianNB

In [290]:
Y_train

array([0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 0.

In [291]:
gnb= GaussianNB()
gnb.fit(X_train,Y_train)

GaussianNB()

In [292]:
y_pred = gnb.predict(X_test)

In [293]:
from sklearn.metrics import confusion_matrix

In [294]:
cm = confusion_matrix(Y_test,y_pred)
cm



array([[46, 27],
       [10, 58]], dtype=int64)

In [295]:
gnb.score(X_train,Y_train)

0.9271758436944938

In [296]:
gnb.predict()

TypeError: _BaseNB.predict() missing 1 required positional argument: 'X'

In [ ]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)